/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IActionRegistry {
  export type AdapterInfoStruct = {
    adapter: AddressLike;
    isActive: boolean;
    gasLimit: BigNumberish;
    requiresTokens: boolean;
  };

  export type AdapterInfoStructOutput = [
    adapter: string,
    isActive: boolean,
    gasLimit: bigint,
    requiresTokens: boolean
  ] & {
    adapter: string;
    isActive: boolean;
    gasLimit: bigint;
    requiresTokens: boolean;
  };
}

export interface IActionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveProtocol"
      | "deactivateAdapter"
      | "getAdapter"
      | "getAdapterByAddress"
      | "isActionAllowed"
      | "isProtocolApproved"
      | "registerAdapter"
      | "revokeProtocol"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdapterDeactivated"
      | "AdapterRegistered"
      | "ProtocolApproved"
      | "ProtocolRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveProtocol",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAdapter",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdapter",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdapterByAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isActionAllowed",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProtocolApproved",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAdapter",
    values: [BytesLike, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeProtocol",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAdapter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAdapterByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isActionAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProtocolApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAdapter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeProtocol",
    data: BytesLike
  ): Result;
}

export namespace AdapterDeactivatedEvent {
  export type InputTuple = [selector: BytesLike];
  export type OutputTuple = [selector: string];
  export interface OutputObject {
    selector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdapterRegisteredEvent {
  export type InputTuple = [selector: BytesLike, adapter: AddressLike];
  export type OutputTuple = [selector: string, adapter: string];
  export interface OutputObject {
    selector: string;
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolApprovedEvent {
  export type InputTuple = [protocol: AddressLike];
  export type OutputTuple = [protocol: string];
  export interface OutputObject {
    protocol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolRevokedEvent {
  export type InputTuple = [protocol: AddressLike];
  export type OutputTuple = [protocol: string];
  export interface OutputObject {
    protocol: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IActionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IActionRegistry;
  waitForDeployment(): Promise<this>;

  interface: IActionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveProtocol: TypedContractMethod<
    [protocol: AddressLike],
    [void],
    "nonpayable"
  >;

  deactivateAdapter: TypedContractMethod<
    [selector: BytesLike],
    [void],
    "nonpayable"
  >;

  getAdapter: TypedContractMethod<
    [selector: BytesLike],
    [IActionRegistry.AdapterInfoStructOutput],
    "view"
  >;

  getAdapterByAddress: TypedContractMethod<
    [adapterAddr: AddressLike],
    [IActionRegistry.AdapterInfoStructOutput],
    "view"
  >;

  isActionAllowed: TypedContractMethod<
    [selector: BytesLike, protocol: AddressLike],
    [boolean],
    "view"
  >;

  isProtocolApproved: TypedContractMethod<
    [protocol: AddressLike],
    [boolean],
    "view"
  >;

  registerAdapter: TypedContractMethod<
    [
      selector: BytesLike,
      adapter: AddressLike,
      gasLimit: BigNumberish,
      requiresTokens: boolean
    ],
    [void],
    "nonpayable"
  >;

  revokeProtocol: TypedContractMethod<
    [protocol: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveProtocol"
  ): TypedContractMethod<[protocol: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateAdapter"
  ): TypedContractMethod<[selector: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAdapter"
  ): TypedContractMethod<
    [selector: BytesLike],
    [IActionRegistry.AdapterInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAdapterByAddress"
  ): TypedContractMethod<
    [adapterAddr: AddressLike],
    [IActionRegistry.AdapterInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isActionAllowed"
  ): TypedContractMethod<
    [selector: BytesLike, protocol: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isProtocolApproved"
  ): TypedContractMethod<[protocol: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAdapter"
  ): TypedContractMethod<
    [
      selector: BytesLike,
      adapter: AddressLike,
      gasLimit: BigNumberish,
      requiresTokens: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeProtocol"
  ): TypedContractMethod<[protocol: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AdapterDeactivated"
  ): TypedContractEvent<
    AdapterDeactivatedEvent.InputTuple,
    AdapterDeactivatedEvent.OutputTuple,
    AdapterDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AdapterRegistered"
  ): TypedContractEvent<
    AdapterRegisteredEvent.InputTuple,
    AdapterRegisteredEvent.OutputTuple,
    AdapterRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolApproved"
  ): TypedContractEvent<
    ProtocolApprovedEvent.InputTuple,
    ProtocolApprovedEvent.OutputTuple,
    ProtocolApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolRevoked"
  ): TypedContractEvent<
    ProtocolRevokedEvent.InputTuple,
    ProtocolRevokedEvent.OutputTuple,
    ProtocolRevokedEvent.OutputObject
  >;

  filters: {
    "AdapterDeactivated(bytes4)": TypedContractEvent<
      AdapterDeactivatedEvent.InputTuple,
      AdapterDeactivatedEvent.OutputTuple,
      AdapterDeactivatedEvent.OutputObject
    >;
    AdapterDeactivated: TypedContractEvent<
      AdapterDeactivatedEvent.InputTuple,
      AdapterDeactivatedEvent.OutputTuple,
      AdapterDeactivatedEvent.OutputObject
    >;

    "AdapterRegistered(bytes4,address)": TypedContractEvent<
      AdapterRegisteredEvent.InputTuple,
      AdapterRegisteredEvent.OutputTuple,
      AdapterRegisteredEvent.OutputObject
    >;
    AdapterRegistered: TypedContractEvent<
      AdapterRegisteredEvent.InputTuple,
      AdapterRegisteredEvent.OutputTuple,
      AdapterRegisteredEvent.OutputObject
    >;

    "ProtocolApproved(address)": TypedContractEvent<
      ProtocolApprovedEvent.InputTuple,
      ProtocolApprovedEvent.OutputTuple,
      ProtocolApprovedEvent.OutputObject
    >;
    ProtocolApproved: TypedContractEvent<
      ProtocolApprovedEvent.InputTuple,
      ProtocolApprovedEvent.OutputTuple,
      ProtocolApprovedEvent.OutputObject
    >;

    "ProtocolRevoked(address)": TypedContractEvent<
      ProtocolRevokedEvent.InputTuple,
      ProtocolRevokedEvent.OutputTuple,
      ProtocolRevokedEvent.OutputObject
    >;
    ProtocolRevoked: TypedContractEvent<
      ProtocolRevokedEvent.InputTuple,
      ProtocolRevokedEvent.OutputTuple,
      ProtocolRevokedEvent.OutputObject
    >;
  };
}
