/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IExecutorHub {
  export type ExecutorStruct = {
    addr: AddressLike;
    stakedAmount: BigNumberish;
    registeredAt: BigNumberish;
    totalExecutions: BigNumberish;
    successfulExecutions: BigNumberish;
    failedExecutions: BigNumberish;
    reputationScore: BigNumberish;
    isActive: boolean;
    isSlashed: boolean;
  };

  export type ExecutorStructOutput = [
    addr: string,
    stakedAmount: bigint,
    registeredAt: bigint,
    totalExecutions: bigint,
    successfulExecutions: bigint,
    failedExecutions: bigint,
    reputationScore: bigint,
    isActive: boolean,
    isSlashed: boolean
  ] & {
    addr: string;
    stakedAmount: bigint;
    registeredAt: bigint;
    totalExecutions: bigint;
    successfulExecutions: bigint;
    failedExecutions: bigint;
    reputationScore: bigint;
    isActive: boolean;
    isSlashed: boolean;
  };
}

export interface IExecutorHubInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addStake"
      | "canExecute"
      | "executeTask"
      | "getExecutor"
      | "recordExecution"
      | "registerExecutor"
      | "slashExecutor"
      | "unregisterExecutor"
      | "withdrawStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutionCompleted"
      | "ExecutorRegistered"
      | "ExecutorSlashed"
      | "ExecutorUnregistered"
      | "StakeAdded"
      | "StakeWithdrawn"
  ): EventFragment;

  encodeFunctionData(functionFragment: "addStake", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canExecute",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordExecution",
    values: [BigNumberish, AddressLike, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerExecutor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "slashExecutor",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "unregisterExecutor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unregisterExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;
}

export namespace ExecutionCompletedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    executor: AddressLike,
    success: boolean
  ];
  export type OutputTuple = [
    taskId: bigint,
    executor: string,
    success: boolean
  ];
  export interface OutputObject {
    taskId: bigint;
    executor: string;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRegisteredEvent {
  export type InputTuple = [executor: AddressLike, stakeAmount: BigNumberish];
  export type OutputTuple = [executor: string, stakeAmount: bigint];
  export interface OutputObject {
    executor: string;
    stakeAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorSlashedEvent {
  export type InputTuple = [
    executor: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [executor: string, amount: bigint, reason: string];
  export interface OutputObject {
    executor: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorUnregisteredEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeAddedEvent {
  export type InputTuple = [executor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [executor: string, amount: bigint];
  export interface OutputObject {
    executor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [executor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [executor: string, amount: bigint];
  export interface OutputObject {
    executor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IExecutorHub extends BaseContract {
  connect(runner?: ContractRunner | null): IExecutorHub;
  waitForDeployment(): Promise<this>;

  interface: IExecutorHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addStake: TypedContractMethod<[], [void], "payable">;

  canExecute: TypedContractMethod<[executor: AddressLike], [boolean], "view">;

  executeTask: TypedContractMethod<
    [taskId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getExecutor: TypedContractMethod<
    [executor: AddressLike],
    [IExecutorHub.ExecutorStructOutput],
    "view"
  >;

  recordExecution: TypedContractMethod<
    [
      taskId: BigNumberish,
      executor: AddressLike,
      success: boolean,
      gasUsed: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  registerExecutor: TypedContractMethod<[], [void], "payable">;

  slashExecutor: TypedContractMethod<
    [executor: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  unregisterExecutor: TypedContractMethod<[], [void], "nonpayable">;

  withdrawStake: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addStake"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<[executor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeTask"
  ): TypedContractMethod<[taskId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getExecutor"
  ): TypedContractMethod<
    [executor: AddressLike],
    [IExecutorHub.ExecutorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "recordExecution"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      executor: AddressLike,
      success: boolean,
      gasUsed: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerExecutor"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "slashExecutor"
  ): TypedContractMethod<
    [executor: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unregisterExecutor"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawStake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ExecutionCompleted"
  ): TypedContractEvent<
    ExecutionCompletedEvent.InputTuple,
    ExecutionCompletedEvent.OutputTuple,
    ExecutionCompletedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRegistered"
  ): TypedContractEvent<
    ExecutorRegisteredEvent.InputTuple,
    ExecutorRegisteredEvent.OutputTuple,
    ExecutorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorSlashed"
  ): TypedContractEvent<
    ExecutorSlashedEvent.InputTuple,
    ExecutorSlashedEvent.OutputTuple,
    ExecutorSlashedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorUnregistered"
  ): TypedContractEvent<
    ExecutorUnregisteredEvent.InputTuple,
    ExecutorUnregisteredEvent.OutputTuple,
    ExecutorUnregisteredEvent.OutputObject
  >;
  getEvent(
    key: "StakeAdded"
  ): TypedContractEvent<
    StakeAddedEvent.InputTuple,
    StakeAddedEvent.OutputTuple,
    StakeAddedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;

  filters: {
    "ExecutionCompleted(uint256,address,bool)": TypedContractEvent<
      ExecutionCompletedEvent.InputTuple,
      ExecutionCompletedEvent.OutputTuple,
      ExecutionCompletedEvent.OutputObject
    >;
    ExecutionCompleted: TypedContractEvent<
      ExecutionCompletedEvent.InputTuple,
      ExecutionCompletedEvent.OutputTuple,
      ExecutionCompletedEvent.OutputObject
    >;

    "ExecutorRegistered(address,uint256)": TypedContractEvent<
      ExecutorRegisteredEvent.InputTuple,
      ExecutorRegisteredEvent.OutputTuple,
      ExecutorRegisteredEvent.OutputObject
    >;
    ExecutorRegistered: TypedContractEvent<
      ExecutorRegisteredEvent.InputTuple,
      ExecutorRegisteredEvent.OutputTuple,
      ExecutorRegisteredEvent.OutputObject
    >;

    "ExecutorSlashed(address,uint256,string)": TypedContractEvent<
      ExecutorSlashedEvent.InputTuple,
      ExecutorSlashedEvent.OutputTuple,
      ExecutorSlashedEvent.OutputObject
    >;
    ExecutorSlashed: TypedContractEvent<
      ExecutorSlashedEvent.InputTuple,
      ExecutorSlashedEvent.OutputTuple,
      ExecutorSlashedEvent.OutputObject
    >;

    "ExecutorUnregistered(address)": TypedContractEvent<
      ExecutorUnregisteredEvent.InputTuple,
      ExecutorUnregisteredEvent.OutputTuple,
      ExecutorUnregisteredEvent.OutputObject
    >;
    ExecutorUnregistered: TypedContractEvent<
      ExecutorUnregisteredEvent.InputTuple,
      ExecutorUnregisteredEvent.OutputTuple,
      ExecutorUnregisteredEvent.OutputObject
    >;

    "StakeAdded(address,uint256)": TypedContractEvent<
      StakeAddedEvent.InputTuple,
      StakeAddedEvent.OutputTuple,
      StakeAddedEvent.OutputObject
    >;
    StakeAdded: TypedContractEvent<
      StakeAddedEvent.InputTuple,
      StakeAddedEvent.OutputTuple,
      StakeAddedEvent.OutputObject
    >;

    "StakeWithdrawn(address,uint256)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
  };
}
