/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ITaskCore {
  export type TaskMetadataStruct = {
    id: BigNumberish;
    creator: AddressLike;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
    maxExecutions: BigNumberish;
    executionCount: BigNumberish;
    lastExecutionTime: BigNumberish;
    recurringInterval: BigNumberish;
    rewardPerExecution: BigNumberish;
    status: BigNumberish;
    conditionHash: BytesLike;
    actionsHash: BytesLike;
    seedCommitment: BytesLike;
  };

  export type TaskMetadataStructOutput = [
    id: bigint,
    creator: string,
    createdAt: bigint,
    expiresAt: bigint,
    maxExecutions: bigint,
    executionCount: bigint,
    lastExecutionTime: bigint,
    recurringInterval: bigint,
    rewardPerExecution: bigint,
    status: bigint,
    conditionHash: string,
    actionsHash: string,
    seedCommitment: string
  ] & {
    id: bigint;
    creator: string;
    createdAt: bigint;
    expiresAt: bigint;
    maxExecutions: bigint;
    executionCount: bigint;
    lastExecutionTime: bigint;
    recurringInterval: bigint;
    rewardPerExecution: bigint;
    status: bigint;
    conditionHash: string;
    actionsHash: string;
    seedCommitment: string;
  };
}

export interface ITaskCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancel"
      | "completeExecution"
      | "creator"
      | "executeTask"
      | "getMetadata"
      | "initialize"
      | "isExecutable"
      | "logic"
      | "pause"
      | "resume"
      | "taskId"
      | "updateReward"
      | "vault"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TaskCancelled"
      | "TaskExecuted"
      | "TaskRewardUpdated"
      | "TaskStatusChanged"
  ): EventFragment;

  encodeFunctionData(functionFragment: "cancel", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "completeExecution",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "creator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeTask",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BigNumberish,
      AddressLike,
      AddressLike,
      AddressLike,
      ITaskCore.TaskMetadataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutable",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "logic", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "resume", values?: undefined): string;
  encodeFunctionData(functionFragment: "taskId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "vault", values?: undefined): string;

  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "creator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isExecutable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logic", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resume", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "taskId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vault", data: BytesLike): Result;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BigNumberish, creator: AddressLike];
  export type OutputTuple = [taskId: bigint, creator: string];
  export interface OutputObject {
    taskId: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskExecutedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    executor: AddressLike,
    success: boolean,
    reward: BigNumberish,
    gasUsed: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    executor: string,
    success: boolean,
    reward: bigint,
    gasUsed: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    executor: string;
    success: boolean;
    reward: bigint;
    gasUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskRewardUpdatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    oldReward: BigNumberish,
    newReward: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    oldReward: bigint,
    newReward: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    oldReward: bigint;
    newReward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskStatusChangedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    oldStatus: BigNumberish,
    newStatus: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    oldStatus: bigint,
    newStatus: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    oldStatus: bigint;
    newStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ITaskCore extends BaseContract {
  connect(runner?: ContractRunner | null): ITaskCore;
  waitForDeployment(): Promise<this>;

  interface: ITaskCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancel: TypedContractMethod<[], [bigint], "nonpayable">;

  completeExecution: TypedContractMethod<
    [success: boolean],
    [void],
    "nonpayable"
  >;

  creator: TypedContractMethod<[], [string], "view">;

  executeTask: TypedContractMethod<
    [executor: AddressLike],
    [boolean],
    "nonpayable"
  >;

  getMetadata: TypedContractMethod<
    [],
    [ITaskCore.TaskMetadataStructOutput],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _id: BigNumberish,
      _creator: AddressLike,
      _vault: AddressLike,
      _logic: AddressLike,
      _metadata: ITaskCore.TaskMetadataStruct
    ],
    [void],
    "nonpayable"
  >;

  isExecutable: TypedContractMethod<[], [boolean], "view">;

  logic: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  resume: TypedContractMethod<[], [void], "nonpayable">;

  taskId: TypedContractMethod<[], [bigint], "view">;

  updateReward: TypedContractMethod<
    [newReward: BigNumberish],
    [void],
    "payable"
  >;

  vault: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "completeExecution"
  ): TypedContractMethod<[success: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "executeTask"
  ): TypedContractMethod<[executor: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "getMetadata"
  ): TypedContractMethod<[], [ITaskCore.TaskMetadataStructOutput], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _id: BigNumberish,
      _creator: AddressLike,
      _vault: AddressLike,
      _logic: AddressLike,
      _metadata: ITaskCore.TaskMetadataStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isExecutable"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "logic"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resume"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "taskId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateReward"
  ): TypedContractMethod<[newReward: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "vault"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskExecuted"
  ): TypedContractEvent<
    TaskExecutedEvent.InputTuple,
    TaskExecutedEvent.OutputTuple,
    TaskExecutedEvent.OutputObject
  >;
  getEvent(
    key: "TaskRewardUpdated"
  ): TypedContractEvent<
    TaskRewardUpdatedEvent.InputTuple,
    TaskRewardUpdatedEvent.OutputTuple,
    TaskRewardUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskStatusChanged"
  ): TypedContractEvent<
    TaskStatusChangedEvent.InputTuple,
    TaskStatusChangedEvent.OutputTuple,
    TaskStatusChangedEvent.OutputObject
  >;

  filters: {
    "TaskCancelled(uint256,address)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskExecuted(uint256,address,bool,uint256,uint256)": TypedContractEvent<
      TaskExecutedEvent.InputTuple,
      TaskExecutedEvent.OutputTuple,
      TaskExecutedEvent.OutputObject
    >;
    TaskExecuted: TypedContractEvent<
      TaskExecutedEvent.InputTuple,
      TaskExecutedEvent.OutputTuple,
      TaskExecutedEvent.OutputObject
    >;

    "TaskRewardUpdated(uint256,uint256,uint256)": TypedContractEvent<
      TaskRewardUpdatedEvent.InputTuple,
      TaskRewardUpdatedEvent.OutputTuple,
      TaskRewardUpdatedEvent.OutputObject
    >;
    TaskRewardUpdated: TypedContractEvent<
      TaskRewardUpdatedEvent.InputTuple,
      TaskRewardUpdatedEvent.OutputTuple,
      TaskRewardUpdatedEvent.OutputObject
    >;

    "TaskStatusChanged(uint256,uint8,uint8)": TypedContractEvent<
      TaskStatusChangedEvent.InputTuple,
      TaskStatusChangedEvent.OutputTuple,
      TaskStatusChangedEvent.OutputObject
    >;
    TaskStatusChanged: TypedContractEvent<
      TaskStatusChangedEvent.InputTuple,
      TaskStatusChangedEvent.OutputTuple,
      TaskStatusChangedEvent.OutputObject
    >;
  };
}
