/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IUserVault {
  export type CallStruct = {
    strategy: AddressLike;
    value: BigNumberish;
    params: BytesLike;
  };

  export type CallStructOutput = [
    strategy: string,
    value: bigint,
    params: string
  ] & { strategy: string; value: bigint; params: string };

  export type AutomationStruct = {
    id: BigNumberish;
    strategy: AddressLike;
    params: BytesLike;
    status: BigNumberish;
    createdAt: BigNumberish;
    executionCount: BigNumberish;
    lastExecutionTime: BigNumberish;
    maxExecutions: BigNumberish;
    label: string;
  };

  export type AutomationStructOutput = [
    id: bigint,
    strategy: string,
    params: string,
    status: bigint,
    createdAt: bigint,
    executionCount: bigint,
    lastExecutionTime: bigint,
    maxExecutions: bigint,
    label: string
  ] & {
    id: bigint;
    strategy: string;
    params: string;
    status: bigint;
    createdAt: bigint;
    executionCount: bigint;
    lastExecutionTime: bigint;
    maxExecutions: bigint;
    label: string;
  };

  export type OperatorStruct = {
    account: AddressLike;
    canCreateAutomation: boolean;
    canCancelAutomation: boolean;
    canUpdateAutomation: boolean;
    canExecuteImmediate: boolean;
    active: boolean;
  };

  export type OperatorStructOutput = [
    account: string,
    canCreateAutomation: boolean,
    canCancelAutomation: boolean,
    canUpdateAutomation: boolean,
    canExecuteImmediate: boolean,
    active: boolean
  ] & {
    account: string;
    canCreateAutomation: boolean;
    canCancelAutomation: boolean;
    canUpdateAutomation: boolean;
    canExecuteImmediate: boolean;
    active: boolean;
  };

  export type SpendingRuleStruct = {
    token: AddressLike;
    maxPerExecution: BigNumberish;
    maxPerDay: BigNumberish;
    maxTotal: BigNumberish;
    spentToday: BigNumberish;
    spentTotal: BigNumberish;
    lastDayReset: BigNumberish;
  };

  export type SpendingRuleStructOutput = [
    token: string,
    maxPerExecution: bigint,
    maxPerDay: bigint,
    maxTotal: bigint,
    spentToday: bigint,
    spentTotal: bigint,
    lastDayReset: bigint
  ] & {
    token: string;
    maxPerExecution: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
    spentToday: bigint;
    spentTotal: bigint;
    lastDayReset: bigint;
  };
}

export interface UserVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelAutomation"
      | "createAutomation"
      | "execute"
      | "executeBatch"
      | "executorHub"
      | "getActiveAutomations"
      | "getAutomation"
      | "getAvailableForRewards"
      | "getExecutableAutomations"
      | "getOperator"
      | "getPortfolio"
      | "getSpendingRule"
      | "getVaultInfo"
      | "initialize"
      | "nextAutomationId"
      | "nonce"
      | "owner"
      | "releaseReward"
      | "removeOperator"
      | "setExecutorHub"
      | "setOperator"
      | "setRewardManager"
      | "setSpendingRule"
      | "strategyRegistry"
      | "trackToken"
      | "transferNative"
      | "transferOwnership"
      | "transferToken"
      | "triggerAutomation"
      | "updateAutomation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AutomationCancelled"
      | "AutomationCompleted"
      | "AutomationCreated"
      | "AutomationTriggered"
      | "AutomationUpdated"
      | "Deposited"
      | "ExecutorHubUpdated"
      | "OperatorRemoved"
      | "OperatorSet"
      | "OwnershipTransferred"
      | "RewardManagerUpdated"
      | "RewardReleased"
      | "SpendingRuleSet"
      | "StrategyExecuted"
      | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelAutomation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createAutomation",
    values: [AddressLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBatch",
    values: [IUserVault.CallStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "executorHub",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveAutomations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAutomation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableForRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutableAutomations",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPortfolio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSpendingRule",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVaultInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextAutomationId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nonce", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutorHub",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, boolean, boolean, boolean, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSpendingRule",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trackToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferNative",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerAutomation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAutomation",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executorHub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveAutomations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableForRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutableAutomations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPortfolio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSpendingRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVaultInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextAutomationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nonce", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutorHub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSpendingRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "strategyRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trackToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAutomation",
    data: BytesLike
  ): Result;
}

export namespace AutomationCancelledEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutomationCompletedEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutomationCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    strategy: AddressLike,
    label: string
  ];
  export type OutputTuple = [id: bigint, strategy: string, label: string];
  export interface OutputObject {
    id: bigint;
    strategy: string;
    label: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutomationTriggeredEvent {
  export type InputTuple = [
    id: BigNumberish,
    success: boolean,
    executionNumber: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    success: boolean,
    executionNumber: bigint
  ];
  export interface OutputObject {
    id: bigint;
    success: boolean;
    executionNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AutomationUpdatedEvent {
  export type InputTuple = [id: BigNumberish, newParams: BytesLike];
  export type OutputTuple = [id: bigint, newParams: string];
  export interface OutputObject {
    id: bigint;
    newParams: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorHubUpdatedEvent {
  export type InputTuple = [oldHub: AddressLike, newHub: AddressLike];
  export type OutputTuple = [oldHub: string, newHub: string];
  export interface OutputObject {
    oldHub: string;
    newHub: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorRemovedEvent {
  export type InputTuple = [operator: AddressLike];
  export type OutputTuple = [operator: string];
  export interface OutputObject {
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorSetEvent {
  export type InputTuple = [
    operator: AddressLike,
    canCreate: boolean,
    canCancel: boolean,
    canUpdate: boolean,
    canExecute: boolean
  ];
  export type OutputTuple = [
    operator: string,
    canCreate: boolean,
    canCancel: boolean,
    canUpdate: boolean,
    canExecute: boolean
  ];
  export interface OutputObject {
    operator: string;
    canCreate: boolean;
    canCancel: boolean;
    canUpdate: boolean;
    canExecute: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardManagerUpdatedEvent {
  export type InputTuple = [oldManager: AddressLike, newManager: AddressLike];
  export type OutputTuple = [oldManager: string, newManager: string];
  export interface OutputObject {
    oldManager: string;
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardReleasedEvent {
  export type InputTuple = [executor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [executor: string, amount: bigint];
  export interface OutputObject {
    executor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendingRuleSetEvent {
  export type InputTuple = [
    operator: AddressLike,
    token: AddressLike,
    maxPerExec: BigNumberish,
    maxPerDay: BigNumberish,
    maxTotal: BigNumberish
  ];
  export type OutputTuple = [
    operator: string,
    token: string,
    maxPerExec: bigint,
    maxPerDay: bigint,
    maxTotal: bigint
  ];
  export interface OutputObject {
    operator: string;
    token: string;
    maxPerExec: bigint;
    maxPerDay: bigint;
    maxTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyExecutedEvent {
  export type InputTuple = [
    strategy: AddressLike,
    success: boolean,
    nonce: BigNumberish
  ];
  export type OutputTuple = [strategy: string, success: boolean, nonce: bigint];
  export interface OutputObject {
    strategy: string;
    success: boolean;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UserVault extends BaseContract {
  connect(runner?: ContractRunner | null): UserVault;
  waitForDeployment(): Promise<this>;

  interface: UserVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelAutomation: TypedContractMethod<
    [automationId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createAutomation: TypedContractMethod<
    [
      strategy: AddressLike,
      params: BytesLike,
      maxExecutions: BigNumberish,
      label: string
    ],
    [bigint],
    "nonpayable"
  >;

  execute: TypedContractMethod<
    [strategy: AddressLike, value: BigNumberish, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;

  executeBatch: TypedContractMethod<
    [calls: IUserVault.CallStruct[]],
    [boolean[]],
    "nonpayable"
  >;

  executorHub: TypedContractMethod<[], [string], "view">;

  getActiveAutomations: TypedContractMethod<
    [],
    [IUserVault.AutomationStructOutput[]],
    "view"
  >;

  getAutomation: TypedContractMethod<
    [id: BigNumberish],
    [IUserVault.AutomationStructOutput],
    "view"
  >;

  getAvailableForRewards: TypedContractMethod<[], [bigint], "view">;

  getExecutableAutomations: TypedContractMethod<[], [bigint[]], "view">;

  getOperator: TypedContractMethod<
    [operator: AddressLike],
    [IUserVault.OperatorStructOutput],
    "view"
  >;

  getPortfolio: TypedContractMethod<
    [],
    [
      [string[], bigint[], bigint] & {
        tokens: string[];
        balances: bigint[];
        nativeBalance: bigint;
      }
    ],
    "view"
  >;

  getSpendingRule: TypedContractMethod<
    [operator: AddressLike, token: AddressLike],
    [IUserVault.SpendingRuleStructOutput],
    "view"
  >;

  getVaultInfo: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint] & {
        vaultOwner: string;
        registry: string;
        hub: string;
        automationCount: bigint;
        currentNonce: bigint;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _owner: AddressLike,
      _strategyRegistry: AddressLike,
      _executorHub: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  nextAutomationId: TypedContractMethod<[], [bigint], "view">;

  nonce: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  releaseReward: TypedContractMethod<
    [executor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  setExecutorHub: TypedContractMethod<
    [newHub: AddressLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [
      operator: AddressLike,
      canCreateAutomation: boolean,
      canCancelAutomation: boolean,
      canUpdateAutomation: boolean,
      canExecuteImmediate: boolean
    ],
    [void],
    "nonpayable"
  >;

  setRewardManager: TypedContractMethod<
    [newRewardManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setSpendingRule: TypedContractMethod<
    [
      operator: AddressLike,
      token: AddressLike,
      maxPerExecution: BigNumberish,
      maxPerDay: BigNumberish,
      maxTotal: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  strategyRegistry: TypedContractMethod<[], [string], "view">;

  trackToken: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  transferNative: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferToken: TypedContractMethod<
    [token: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  triggerAutomation: TypedContractMethod<
    [automationId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  updateAutomation: TypedContractMethod<
    [automationId: BigNumberish, newParams: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelAutomation"
  ): TypedContractMethod<[automationId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createAutomation"
  ): TypedContractMethod<
    [
      strategy: AddressLike,
      params: BytesLike,
      maxExecutions: BigNumberish,
      label: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [strategy: AddressLike, value: BigNumberish, params: BytesLike],
    [[boolean, string] & { success: boolean; result: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeBatch"
  ): TypedContractMethod<
    [calls: IUserVault.CallStruct[]],
    [boolean[]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executorHub"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getActiveAutomations"
  ): TypedContractMethod<[], [IUserVault.AutomationStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getAutomation"
  ): TypedContractMethod<
    [id: BigNumberish],
    [IUserVault.AutomationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAvailableForRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExecutableAutomations"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getOperator"
  ): TypedContractMethod<
    [operator: AddressLike],
    [IUserVault.OperatorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPortfolio"
  ): TypedContractMethod<
    [],
    [
      [string[], bigint[], bigint] & {
        tokens: string[];
        balances: bigint[];
        nativeBalance: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSpendingRule"
  ): TypedContractMethod<
    [operator: AddressLike, token: AddressLike],
    [IUserVault.SpendingRuleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVaultInfo"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, bigint] & {
        vaultOwner: string;
        registry: string;
        hub: string;
        automationCount: bigint;
        currentNonce: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _owner: AddressLike,
      _strategyRegistry: AddressLike,
      _executorHub: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextAutomationId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseReward"
  ): TypedContractMethod<
    [executor: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExecutorHub"
  ): TypedContractMethod<[newHub: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      canCreateAutomation: boolean,
      canCancelAutomation: boolean,
      canUpdateAutomation: boolean,
      canExecuteImmediate: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRewardManager"
  ): TypedContractMethod<[newRewardManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSpendingRule"
  ): TypedContractMethod<
    [
      operator: AddressLike,
      token: AddressLike,
      maxPerExecution: BigNumberish,
      maxPerDay: BigNumberish,
      maxTotal: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "strategyRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "trackToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferNative"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferToken"
  ): TypedContractMethod<
    [token: AddressLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "triggerAutomation"
  ): TypedContractMethod<[automationId: BigNumberish], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAutomation"
  ): TypedContractMethod<
    [automationId: BigNumberish, newParams: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AutomationCancelled"
  ): TypedContractEvent<
    AutomationCancelledEvent.InputTuple,
    AutomationCancelledEvent.OutputTuple,
    AutomationCancelledEvent.OutputObject
  >;
  getEvent(
    key: "AutomationCompleted"
  ): TypedContractEvent<
    AutomationCompletedEvent.InputTuple,
    AutomationCompletedEvent.OutputTuple,
    AutomationCompletedEvent.OutputObject
  >;
  getEvent(
    key: "AutomationCreated"
  ): TypedContractEvent<
    AutomationCreatedEvent.InputTuple,
    AutomationCreatedEvent.OutputTuple,
    AutomationCreatedEvent.OutputObject
  >;
  getEvent(
    key: "AutomationTriggered"
  ): TypedContractEvent<
    AutomationTriggeredEvent.InputTuple,
    AutomationTriggeredEvent.OutputTuple,
    AutomationTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "AutomationUpdated"
  ): TypedContractEvent<
    AutomationUpdatedEvent.InputTuple,
    AutomationUpdatedEvent.OutputTuple,
    AutomationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorHubUpdated"
  ): TypedContractEvent<
    ExecutorHubUpdatedEvent.InputTuple,
    ExecutorHubUpdatedEvent.OutputTuple,
    ExecutorHubUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorRemoved"
  ): TypedContractEvent<
    OperatorRemovedEvent.InputTuple,
    OperatorRemovedEvent.OutputTuple,
    OperatorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorSet"
  ): TypedContractEvent<
    OperatorSetEvent.InputTuple,
    OperatorSetEvent.OutputTuple,
    OperatorSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardManagerUpdated"
  ): TypedContractEvent<
    RewardManagerUpdatedEvent.InputTuple,
    RewardManagerUpdatedEvent.OutputTuple,
    RewardManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardReleased"
  ): TypedContractEvent<
    RewardReleasedEvent.InputTuple,
    RewardReleasedEvent.OutputTuple,
    RewardReleasedEvent.OutputObject
  >;
  getEvent(
    key: "SpendingRuleSet"
  ): TypedContractEvent<
    SpendingRuleSetEvent.InputTuple,
    SpendingRuleSetEvent.OutputTuple,
    SpendingRuleSetEvent.OutputObject
  >;
  getEvent(
    key: "StrategyExecuted"
  ): TypedContractEvent<
    StrategyExecutedEvent.InputTuple,
    StrategyExecutedEvent.OutputTuple,
    StrategyExecutedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "AutomationCancelled(uint256)": TypedContractEvent<
      AutomationCancelledEvent.InputTuple,
      AutomationCancelledEvent.OutputTuple,
      AutomationCancelledEvent.OutputObject
    >;
    AutomationCancelled: TypedContractEvent<
      AutomationCancelledEvent.InputTuple,
      AutomationCancelledEvent.OutputTuple,
      AutomationCancelledEvent.OutputObject
    >;

    "AutomationCompleted(uint256)": TypedContractEvent<
      AutomationCompletedEvent.InputTuple,
      AutomationCompletedEvent.OutputTuple,
      AutomationCompletedEvent.OutputObject
    >;
    AutomationCompleted: TypedContractEvent<
      AutomationCompletedEvent.InputTuple,
      AutomationCompletedEvent.OutputTuple,
      AutomationCompletedEvent.OutputObject
    >;

    "AutomationCreated(uint256,address,string)": TypedContractEvent<
      AutomationCreatedEvent.InputTuple,
      AutomationCreatedEvent.OutputTuple,
      AutomationCreatedEvent.OutputObject
    >;
    AutomationCreated: TypedContractEvent<
      AutomationCreatedEvent.InputTuple,
      AutomationCreatedEvent.OutputTuple,
      AutomationCreatedEvent.OutputObject
    >;

    "AutomationTriggered(uint256,bool,uint256)": TypedContractEvent<
      AutomationTriggeredEvent.InputTuple,
      AutomationTriggeredEvent.OutputTuple,
      AutomationTriggeredEvent.OutputObject
    >;
    AutomationTriggered: TypedContractEvent<
      AutomationTriggeredEvent.InputTuple,
      AutomationTriggeredEvent.OutputTuple,
      AutomationTriggeredEvent.OutputObject
    >;

    "AutomationUpdated(uint256,bytes)": TypedContractEvent<
      AutomationUpdatedEvent.InputTuple,
      AutomationUpdatedEvent.OutputTuple,
      AutomationUpdatedEvent.OutputObject
    >;
    AutomationUpdated: TypedContractEvent<
      AutomationUpdatedEvent.InputTuple,
      AutomationUpdatedEvent.OutputTuple,
      AutomationUpdatedEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "ExecutorHubUpdated(address,address)": TypedContractEvent<
      ExecutorHubUpdatedEvent.InputTuple,
      ExecutorHubUpdatedEvent.OutputTuple,
      ExecutorHubUpdatedEvent.OutputObject
    >;
    ExecutorHubUpdated: TypedContractEvent<
      ExecutorHubUpdatedEvent.InputTuple,
      ExecutorHubUpdatedEvent.OutputTuple,
      ExecutorHubUpdatedEvent.OutputObject
    >;

    "OperatorRemoved(address)": TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;
    OperatorRemoved: TypedContractEvent<
      OperatorRemovedEvent.InputTuple,
      OperatorRemovedEvent.OutputTuple,
      OperatorRemovedEvent.OutputObject
    >;

    "OperatorSet(address,bool,bool,bool,bool)": TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;
    OperatorSet: TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardManagerUpdated(address,address)": TypedContractEvent<
      RewardManagerUpdatedEvent.InputTuple,
      RewardManagerUpdatedEvent.OutputTuple,
      RewardManagerUpdatedEvent.OutputObject
    >;
    RewardManagerUpdated: TypedContractEvent<
      RewardManagerUpdatedEvent.InputTuple,
      RewardManagerUpdatedEvent.OutputTuple,
      RewardManagerUpdatedEvent.OutputObject
    >;

    "RewardReleased(address,uint256)": TypedContractEvent<
      RewardReleasedEvent.InputTuple,
      RewardReleasedEvent.OutputTuple,
      RewardReleasedEvent.OutputObject
    >;
    RewardReleased: TypedContractEvent<
      RewardReleasedEvent.InputTuple,
      RewardReleasedEvent.OutputTuple,
      RewardReleasedEvent.OutputObject
    >;

    "SpendingRuleSet(address,address,uint256,uint256,uint256)": TypedContractEvent<
      SpendingRuleSetEvent.InputTuple,
      SpendingRuleSetEvent.OutputTuple,
      SpendingRuleSetEvent.OutputObject
    >;
    SpendingRuleSet: TypedContractEvent<
      SpendingRuleSetEvent.InputTuple,
      SpendingRuleSetEvent.OutputTuple,
      SpendingRuleSetEvent.OutputObject
    >;

    "StrategyExecuted(address,bool,uint256)": TypedContractEvent<
      StrategyExecutedEvent.InputTuple,
      StrategyExecutedEvent.OutputTuple,
      StrategyExecutedEvent.OutputObject
    >;
    StrategyExecuted: TypedContractEvent<
      StrategyExecutedEvent.InputTuple,
      StrategyExecutedEvent.OutputTuple,
      StrategyExecutedEvent.OutputObject
    >;

    "Withdrawn(address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
