/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface StorkPriceTransferAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canExecute"
      | "execute"
      | "getTokenRequirements"
      | "isProtocolSupported"
      | "name"
      | "validateParams"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ActionExecuted"): EventFragment;

  encodeFunctionData(
    functionFragment: "canExecute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenRequirements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProtocolSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "validateParams",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProtocolSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateParams",
    data: BytesLike
  ): Result;
}

export namespace ActionExecutedEvent {
  export type InputTuple = [
    vault: AddressLike,
    protocol: AddressLike,
    success: boolean,
    result: BytesLike
  ];
  export type OutputTuple = [
    vault: string,
    protocol: string,
    success: boolean,
    result: string
  ];
  export interface OutputObject {
    vault: string;
    protocol: string;
    success: boolean;
    result: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StorkPriceTransferAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): StorkPriceTransferAdapter;
  waitForDeployment(): Promise<this>;

  interface: StorkPriceTransferAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canExecute: TypedContractMethod<
    [params: BytesLike],
    [[boolean, string]],
    "view"
  >;

  execute: TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string]],
    "nonpayable"
  >;

  getTokenRequirements: TypedContractMethod<
    [params: BytesLike],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;

  isProtocolSupported: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  validateParams: TypedContractMethod<
    [params: BytesLike],
    [[boolean, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<[params: BytesLike], [[boolean, string]], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTokenRequirements"
  ): TypedContractMethod<
    [params: BytesLike],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isProtocolSupported"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validateParams"
  ): TypedContractMethod<[params: BytesLike], [[boolean, string]], "view">;

  getEvent(
    key: "ActionExecuted"
  ): TypedContractEvent<
    ActionExecutedEvent.InputTuple,
    ActionExecutedEvent.OutputTuple,
    ActionExecutedEvent.OutputObject
  >;

  filters: {
    "ActionExecuted(address,address,bool,bytes)": TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;
    ActionExecuted: TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;
  };
}
