/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IRewardManager {
  export type RewardCalculationStruct = {
    executorReward: BigNumberish;
    platformFee: BigNumberish;
    gasReimbursement: BigNumberish;
    totalFromVault: BigNumberish;
  };

  export type RewardCalculationStructOutput = [
    executorReward: bigint,
    platformFee: bigint,
    gasReimbursement: bigint,
    totalFromVault: bigint
  ] & {
    executorReward: bigint;
    platformFee: bigint;
    gasReimbursement: bigint;
    totalFromVault: bigint;
  };
}

export interface RewardManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BASIS_POINTS"
      | "MAX_PLATFORM_FEE"
      | "calculateReward"
      | "collectFees"
      | "distributeReward"
      | "executorHub"
      | "gasReimbursementMultiplier"
      | "getReputationMultiplier"
      | "owner"
      | "platformFeePercentage"
      | "renounceOwnership"
      | "setExecutorHub"
      | "setGasReimbursementMultiplier"
      | "setPlatformFee"
      | "setTaskLogic"
      | "taskLogic"
      | "totalFeesCollected"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Calcuated"
      | "OwnershipTransferred"
      | "PlatformFeeCollected"
      | "PlatformFeeUpdated"
      | "RewardDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BASIS_POINTS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateReward",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeReward",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executorHub",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gasReimbursementMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReputationMultiplier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setExecutorHub",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGasReimbursementMultiplier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTaskLogic",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "taskLogic", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalFeesCollected",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "BASIS_POINTS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executorHub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gasReimbursementMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReputationMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setExecutorHub",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGasReimbursementMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTaskLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "taskLogic", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalFeesCollected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CalcuatedEvent {
  export type InputTuple = [calc: BigNumberish];
  export type OutputTuple = [calc: bigint];
  export interface OutputObject {
    calc: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeCollectedEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [oldFee: BigNumberish, newFee: BigNumberish];
  export type OutputTuple = [oldFee: bigint, newFee: bigint];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardDistributedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    executor: AddressLike,
    executorReward: BigNumberish,
    platformFee: BigNumberish,
    gasReimbursement: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    executor: string,
    executorReward: bigint,
    platformFee: bigint,
    gasReimbursement: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    executor: string;
    executorReward: bigint;
    platformFee: bigint;
    gasReimbursement: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardManager extends BaseContract {
  connect(runner?: ContractRunner | null): RewardManager;
  waitForDeployment(): Promise<this>;

  interface: RewardManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BASIS_POINTS: TypedContractMethod<[], [bigint], "view">;

  MAX_PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  calculateReward: TypedContractMethod<
    [baseReward: BigNumberish, executor: AddressLike, gasUsed: BigNumberish],
    [IRewardManager.RewardCalculationStructOutput],
    "view"
  >;

  collectFees: TypedContractMethod<
    [recipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  distributeReward: TypedContractMethod<
    [
      vault: AddressLike,
      executor: AddressLike,
      baseReward: BigNumberish,
      gasUsed: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  executorHub: TypedContractMethod<[], [string], "view">;

  gasReimbursementMultiplier: TypedContractMethod<[], [bigint], "view">;

  getReputationMultiplier: TypedContractMethod<
    [executor: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeePercentage: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setExecutorHub: TypedContractMethod<
    [_executorHub: AddressLike],
    [void],
    "nonpayable"
  >;

  setGasReimbursementMultiplier: TypedContractMethod<
    [_multiplier: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [feePercentage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTaskLogic: TypedContractMethod<
    [_taskLogic: AddressLike],
    [void],
    "nonpayable"
  >;

  taskLogic: TypedContractMethod<[], [string], "view">;

  totalFeesCollected: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BASIS_POINTS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateReward"
  ): TypedContractMethod<
    [baseReward: BigNumberish, executor: AddressLike, gasUsed: BigNumberish],
    [IRewardManager.RewardCalculationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<[recipient: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeReward"
  ): TypedContractMethod<
    [
      vault: AddressLike,
      executor: AddressLike,
      baseReward: BigNumberish,
      gasUsed: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executorHub"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "gasReimbursementMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReputationMultiplier"
  ): TypedContractMethod<[executor: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setExecutorHub"
  ): TypedContractMethod<[_executorHub: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGasReimbursementMultiplier"
  ): TypedContractMethod<[_multiplier: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[feePercentage: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTaskLogic"
  ): TypedContractMethod<[_taskLogic: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "taskLogic"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalFeesCollected"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "Calcuated"
  ): TypedContractEvent<
    CalcuatedEvent.InputTuple,
    CalcuatedEvent.OutputTuple,
    CalcuatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeCollected"
  ): TypedContractEvent<
    PlatformFeeCollectedEvent.InputTuple,
    PlatformFeeCollectedEvent.OutputTuple,
    PlatformFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardDistributed"
  ): TypedContractEvent<
    RewardDistributedEvent.InputTuple,
    RewardDistributedEvent.OutputTuple,
    RewardDistributedEvent.OutputObject
  >;

  filters: {
    "Calcuated(uint256)": TypedContractEvent<
      CalcuatedEvent.InputTuple,
      CalcuatedEvent.OutputTuple,
      CalcuatedEvent.OutputObject
    >;
    Calcuated: TypedContractEvent<
      CalcuatedEvent.InputTuple,
      CalcuatedEvent.OutputTuple,
      CalcuatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlatformFeeCollected(address,uint256)": TypedContractEvent<
      PlatformFeeCollectedEvent.InputTuple,
      PlatformFeeCollectedEvent.OutputTuple,
      PlatformFeeCollectedEvent.OutputObject
    >;
    PlatformFeeCollected: TypedContractEvent<
      PlatformFeeCollectedEvent.InputTuple,
      PlatformFeeCollectedEvent.OutputTuple,
      PlatformFeeCollectedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "RewardDistributed(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
    RewardDistributed: TypedContractEvent<
      RewardDistributedEvent.InputTuple,
      RewardDistributedEvent.OutputTuple,
      RewardDistributedEvent.OutputObject
    >;
  };
}
