/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IStrategyRegistry {
  export type StrategyInfoStruct = {
    adapter: AddressLike;
    isActive: boolean;
    gasLimit: BigNumberish;
    requiresTokens: boolean;
    requiredInBatch: boolean;
    automationOnly: boolean;
    outputTokens: AddressLike[];
  };

  export type StrategyInfoStructOutput = [
    adapter: string,
    isActive: boolean,
    gasLimit: bigint,
    requiresTokens: boolean,
    requiredInBatch: boolean,
    automationOnly: boolean,
    outputTokens: string[]
  ] & {
    adapter: string;
    isActive: boolean;
    gasLimit: bigint;
    requiresTokens: boolean;
    requiredInBatch: boolean;
    automationOnly: boolean;
    outputTokens: string[];
  };
}

export interface StrategyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activateStrategy"
      | "deactivateStrategy"
      | "getAllStrategies"
      | "getStrategyCount"
      | "getStrategyInfo"
      | "getStrategyOutputTokens"
      | "isAutomation"
      | "isRequired"
      | "isStrategyActive"
      | "owner"
      | "registerStrategy"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "StrategyActivated"
      | "StrategyDeactivated"
      | "StrategyRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activateStrategy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateStrategy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllStrategies",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStrategyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStrategyInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStrategyOutputTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAutomation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRequired",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isStrategyActive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerStrategy",
    values: [
      AddressLike,
      BigNumberish,
      boolean,
      boolean,
      boolean,
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllStrategies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrategyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrategyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrategyOutputTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAutomation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isRequired", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isStrategyActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyActivatedEvent {
  export type InputTuple = [adapter: AddressLike];
  export type OutputTuple = [adapter: string];
  export interface OutputObject {
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyDeactivatedEvent {
  export type InputTuple = [adapter: AddressLike];
  export type OutputTuple = [adapter: string];
  export interface OutputObject {
    adapter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyRegisteredEvent {
  export type InputTuple = [
    adapter: AddressLike,
    gasLimit: BigNumberish,
    isAutomation: boolean
  ];
  export type OutputTuple = [
    adapter: string,
    gasLimit: bigint,
    isAutomation: boolean
  ];
  export interface OutputObject {
    adapter: string;
    gasLimit: bigint;
    isAutomation: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrategyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyRegistry;
  waitForDeployment(): Promise<this>;

  interface: StrategyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activateStrategy: TypedContractMethod<
    [adapter: AddressLike],
    [void],
    "nonpayable"
  >;

  deactivateStrategy: TypedContractMethod<
    [adapter: AddressLike],
    [void],
    "nonpayable"
  >;

  getAllStrategies: TypedContractMethod<[], [string[]], "view">;

  getStrategyCount: TypedContractMethod<[], [bigint], "view">;

  getStrategyInfo: TypedContractMethod<
    [adapter: AddressLike],
    [IStrategyRegistry.StrategyInfoStructOutput],
    "view"
  >;

  getStrategyOutputTokens: TypedContractMethod<
    [adapter: AddressLike],
    [string[]],
    "view"
  >;

  isAutomation: TypedContractMethod<[adapter: AddressLike], [boolean], "view">;

  isRequired: TypedContractMethod<[adapter: AddressLike], [boolean], "view">;

  isStrategyActive: TypedContractMethod<
    [adapter: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerStrategy: TypedContractMethod<
    [
      adapter: AddressLike,
      gasLimit: BigNumberish,
      requiresTokens: boolean,
      requiredInBatch: boolean,
      automationOnly: boolean,
      outputTokens: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activateStrategy"
  ): TypedContractMethod<[adapter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deactivateStrategy"
  ): TypedContractMethod<[adapter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllStrategies"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getStrategyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStrategyInfo"
  ): TypedContractMethod<
    [adapter: AddressLike],
    [IStrategyRegistry.StrategyInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStrategyOutputTokens"
  ): TypedContractMethod<[adapter: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isAutomation"
  ): TypedContractMethod<[adapter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRequired"
  ): TypedContractMethod<[adapter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isStrategyActive"
  ): TypedContractMethod<[adapter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerStrategy"
  ): TypedContractMethod<
    [
      adapter: AddressLike,
      gasLimit: BigNumberish,
      requiresTokens: boolean,
      requiredInBatch: boolean,
      automationOnly: boolean,
      outputTokens: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StrategyActivated"
  ): TypedContractEvent<
    StrategyActivatedEvent.InputTuple,
    StrategyActivatedEvent.OutputTuple,
    StrategyActivatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyDeactivated"
  ): TypedContractEvent<
    StrategyDeactivatedEvent.InputTuple,
    StrategyDeactivatedEvent.OutputTuple,
    StrategyDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyRegistered"
  ): TypedContractEvent<
    StrategyRegisteredEvent.InputTuple,
    StrategyRegisteredEvent.OutputTuple,
    StrategyRegisteredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StrategyActivated(address)": TypedContractEvent<
      StrategyActivatedEvent.InputTuple,
      StrategyActivatedEvent.OutputTuple,
      StrategyActivatedEvent.OutputObject
    >;
    StrategyActivated: TypedContractEvent<
      StrategyActivatedEvent.InputTuple,
      StrategyActivatedEvent.OutputTuple,
      StrategyActivatedEvent.OutputObject
    >;

    "StrategyDeactivated(address)": TypedContractEvent<
      StrategyDeactivatedEvent.InputTuple,
      StrategyDeactivatedEvent.OutputTuple,
      StrategyDeactivatedEvent.OutputObject
    >;
    StrategyDeactivated: TypedContractEvent<
      StrategyDeactivatedEvent.InputTuple,
      StrategyDeactivatedEvent.OutputTuple,
      StrategyDeactivatedEvent.OutputObject
    >;

    "StrategyRegistered(address,uint256,bool)": TypedContractEvent<
      StrategyRegisteredEvent.InputTuple,
      StrategyRegisteredEvent.OutputTuple,
      StrategyRegisteredEvent.OutputObject
    >;
    StrategyRegistered: TypedContractEvent<
      StrategyRegisteredEvent.InputTuple,
      StrategyRegisteredEvent.OutputTuple,
      StrategyRegisteredEvent.OutputObject
    >;
  };
}
