/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface UniswapV3LimitOrderAdapterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_HIGH"
      | "FEE_LOW"
      | "FEE_MEDIUM"
      | "PRICE_PRECISION"
      | "canExecute"
      | "execute"
      | "factory"
      | "getCurrentPrice"
      | "getTokenRequirements"
      | "isOrderExecuted"
      | "isProtocolSupported"
      | "name"
      | "orderExecuted"
      | "swapRouter"
      | "validateParams"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ActionExecuted" | "LimitOrderExecuted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "FEE_HIGH", values?: undefined): string;
  encodeFunctionData(functionFragment: "FEE_LOW", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "FEE_MEDIUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canExecute",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenRequirements",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOrderExecuted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isProtocolSupported",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "orderExecuted",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "validateParams",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "FEE_HIGH", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FEE_LOW", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FEE_MEDIUM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canExecute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenRequirements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isOrderExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isProtocolSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orderExecuted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "validateParams",
    data: BytesLike
  ): Result;
}

export namespace ActionExecutedEvent {
  export type InputTuple = [
    vault: AddressLike,
    target: AddressLike,
    success: boolean,
    data: BytesLike
  ];
  export type OutputTuple = [
    vault: string,
    target: string,
    success: boolean,
    data: string
  ];
  export interface OutputObject {
    vault: string;
    target: string;
    success: boolean;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LimitOrderExecutedEvent {
  export type InputTuple = [
    orderId: BytesLike,
    vault: AddressLike,
    orderType: BigNumberish,
    currentPrice: BigNumberish,
    targetPrice: BigNumberish,
    amountIn: BigNumberish,
    amountOut: BigNumberish
  ];
  export type OutputTuple = [
    orderId: string,
    vault: string,
    orderType: bigint,
    currentPrice: bigint,
    targetPrice: bigint,
    amountIn: bigint,
    amountOut: bigint
  ];
  export interface OutputObject {
    orderId: string;
    vault: string;
    orderType: bigint;
    currentPrice: bigint;
    targetPrice: bigint;
    amountIn: bigint;
    amountOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface UniswapV3LimitOrderAdapter extends BaseContract {
  connect(runner?: ContractRunner | null): UniswapV3LimitOrderAdapter;
  waitForDeployment(): Promise<this>;

  interface: UniswapV3LimitOrderAdapterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_HIGH: TypedContractMethod<[], [bigint], "view">;

  FEE_LOW: TypedContractMethod<[], [bigint], "view">;

  FEE_MEDIUM: TypedContractMethod<[], [bigint], "view">;

  PRICE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  canExecute: TypedContractMethod<
    [params: BytesLike],
    [[boolean, string]],
    "view"
  >;

  execute: TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string]],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  getCurrentPrice: TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, fee: BigNumberish],
    [bigint],
    "view"
  >;

  getTokenRequirements: TypedContractMethod<
    [params: BytesLike],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;

  isOrderExecuted: TypedContractMethod<[orderId: BytesLike], [boolean], "view">;

  isProtocolSupported: TypedContractMethod<
    [protocol: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  orderExecuted: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  swapRouter: TypedContractMethod<[], [string], "view">;

  validateParams: TypedContractMethod<
    [params: BytesLike],
    [[boolean, string]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_HIGH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_LOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_MEDIUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "canExecute"
  ): TypedContractMethod<[params: BytesLike], [[boolean, string]], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [vault: AddressLike, params: BytesLike],
    [[boolean, string]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<
    [tokenIn: AddressLike, tokenOut: AddressLike, fee: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenRequirements"
  ): TypedContractMethod<
    [params: BytesLike],
    [[string[], bigint[]] & { tokens: string[]; amounts: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOrderExecuted"
  ): TypedContractMethod<[orderId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isProtocolSupported"
  ): TypedContractMethod<[protocol: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "orderExecuted"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "swapRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "validateParams"
  ): TypedContractMethod<[params: BytesLike], [[boolean, string]], "view">;

  getEvent(
    key: "ActionExecuted"
  ): TypedContractEvent<
    ActionExecutedEvent.InputTuple,
    ActionExecutedEvent.OutputTuple,
    ActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "LimitOrderExecuted"
  ): TypedContractEvent<
    LimitOrderExecutedEvent.InputTuple,
    LimitOrderExecutedEvent.OutputTuple,
    LimitOrderExecutedEvent.OutputObject
  >;

  filters: {
    "ActionExecuted(address,address,bool,bytes)": TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;
    ActionExecuted: TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;

    "LimitOrderExecuted(bytes32,address,uint8,uint256,uint256,uint256,uint256)": TypedContractEvent<
      LimitOrderExecutedEvent.InputTuple,
      LimitOrderExecutedEvent.OutputTuple,
      LimitOrderExecutedEvent.OutputObject
    >;
    LimitOrderExecuted: TypedContractEvent<
      LimitOrderExecutedEvent.InputTuple,
      LimitOrderExecutedEvent.OutputTuple,
      LimitOrderExecutedEvent.OutputObject
    >;
  };
}
