/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockChainlinkAggregator } from "./MockChainlinkAggregator";
export type { MockERC20 } from "./MockERC20";
export type { MockProtocol } from "./MockProtocol";
export type { MockUniswapV2Router } from "./MockUniswapV2Router";
