/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockCurvePool } from "./MockCurvePool";
export type { MockERC20 } from "./MockERC20";
export type { MockStorkOracle } from "./MockStorkOracle";
export type { MockTokenMessenger } from "./MockTokenMessenger";
